FROM public.ecr.aws/lambda/python:3.8

COPY requirements.txt ./
RUN pip install -r requirements.txt

ENV AWS_SHARED_CREDENTIALS_FILE=credentials

COPY readingdb/lamb.py ./

# This (and later layers) cannot be cached because we're
# copying an entire directory
COPY aws/credentials ./
RUN mkdir ./google
COPY google/credentials.json ./google/credentials.json
ADD readingdb ./readingdb 

CMD [ "lamb.handler" ]