FROM python:3

COPY requirements.txt ./
RUN pip install -r requirements.txt

ENV AWS_SHARED_CREDENTIALS_FILE=credentials

COPY aws/credentials ./
ADD readingdb ./readingdb
COPY farg.py ./

CMD [ "echo", "complete" ]